// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUntlMg1Mu2Bl_2vishw2JgwOaNpZY6PY',
    appId: '1:4703622410:web:f37c4d08e266b6b51d96f3',
    messagingSenderId: '4703622410',
    projectId: 'candrawara',
    authDomain: 'candrawara.firebaseapp.com',
    storageBucket: 'candrawara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcP1IW6axi8KEz1vHjYBv-JB628cANlTg',
    appId: '1:4703622410:android:fbe46a48c4fbc2261d96f3',
    messagingSenderId: '4703622410',
    projectId: 'candrawara',
    storageBucket: 'candrawara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJzLd2MV6KrIijZbXupYDS_5r0ms-G-gI',
    appId: '1:4703622410:ios:2cabfe50d581f8ec1d96f3',
    messagingSenderId: '4703622410',
    projectId: 'candrawara',
    storageBucket: 'candrawara.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJzLd2MV6KrIijZbXupYDS_5r0ms-G-gI',
    appId: '1:4703622410:ios:2cabfe50d581f8ec1d96f3',
    messagingSenderId: '4703622410',
    projectId: 'candrawara',
    storageBucket: 'candrawara.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUntlMg1Mu2Bl_2vishw2JgwOaNpZY6PY',
    appId: '1:4703622410:web:8b5ade39f4b045ac1d96f3',
    messagingSenderId: '4703622410',
    projectId: 'candrawara',
    authDomain: 'candrawara.firebaseapp.com',
    storageBucket: 'candrawara.firebasestorage.app',
  );
}
